### PR TITLE
refactor: app folder structure

### PR DESCRIPTION
**Pull request by Ibwedagama**
#### Overview
The previous folders structure had some drawbacks and needed to be refactored to ensure easy project maintenance in the future.

The reasons for this refactor are as follows:

- Page-level components should be in the `/pages` folder to avoid confusion where data-fetching and page-level states are stored
- We need to make sure that only the page-level component has the responsibility to fetch data from the API and render the child components as a representation only
- Reusable components (aka BaseComponents) should be stored in a folder that also holds reusable files
- Constant variables should be stored in a folder that holds reusable files too
- We need to make sure that the folder structure makes sense and is easy to understand

Overview of the new folder structure:
```
src
├── assets
│   ├── icons
│   ├── images
│   └── styles
├── common
│   ├── components
│   ├── constants
│   └── helpers
├── components
│   ├── Agenda
│   ├── Login
│   └── ...
├── layouts
├── mocks
├── pages
│   ├── Agenda
│   └── ...
├── plugins
├── repositories
├── router
└── store
    └── modules
```

Any insight or feedback on the matter would be greatly appreciated ❤️

#### Reference
[How to structure my Vue.js project by Manu Ustenko](https://itnext.io/how-to-structure-my-vue-js-project-e4468db005ac)

### Evidence
title: refactor app folder structure
project: Portal Jabar
participants: @Ibwedagama @bangunbagustapa @maulanayuseph @adzharamrullah @khihadysucahyo @rachadiannovansyah @naufalihsank @yoslie

### CODE REVIEW

**Comment by adzharamrullah** [comment]
wow amazing  ❤️  i really appreciate your work
nice to have if you add stucture directory to readme as documentation this project

**Review by adzharamrullah — APPROVED** [review]

**Review by rachadiannovansyah — APPROVED** [review]
this is great! I should be happier if @bangunbagustapa give him a cup of coffee 😘

**Comment by Ibwedagama** [comment]
> wow amazing ❤️ i really appreciate your work nice to have if you add stucture directory to readme as documentation this project

hello @adzharamrullah , we agree with you 💯

we will improve the documentations and add this folder structure guide to the readme file ASAP cc @bangunbagustapa 👍🏼

**Review by bangunbagustapa — APPROVED** [review]

**Comment by Ibwedagama** [comment]
> this is great! I should be happier if @bangunbagustapa give him a cup of coffee 😘

we should give him a coffee instead, this whole operations are @bangunbagustapa idea 😆

**Comment by bangunbagustapa** [comment]
Nice @adzharamrullah, the documentation is already on our radar here https://github.com/jabardigitalservice/portal-jabar-cms/projects/1#card-75332439

**Review by yoslie — APPROVED** [review]

**Review by naufalihsank — APPROVED** [review]

**Review by khihadysucahyo — APPROVED** [review]
hwaaa great job dab! for doing such a gudd massive refactor 😘

**Review by maulanayuseph — APPROVED** [review]

**Pull request merged**
